def generate_export_script(params):
    """
    Generate a self-contained Python script that reproduces the current CubeFig plot.
    """
    file_path = params.get('file_path') or ''
    mask_path = params.get('mask_path')
    view_type = params.get('view_type', 'cube')
    channel = int(params.get('channel', 0))
    moment_type = str(params.get('moment_type', '0'))
    start_chan = int(params.get('start_chan', 0))
    end_chan = int(params.get('end_chan', 0))
    title = params.get('title', '')
    fig_width = float(params.get('fig_width', 8))
    fig_height = float(params.get('fig_height', 8))
    grid = bool(params.get('grid', False))
    show_beam = bool(params.get('show_beam', False))
    show_center = bool(params.get('show_center', False))
    center_x_raw = params.get('center_x')
    center_y_raw = params.get('center_y')
    show_offset = bool(params.get('show_offset', False))
    offset_angle_unit = params.get('offset_angle_unit', 'arcsec')
    show_physical = bool(params.get('show_physical', False))
    distance_val_raw = params.get('distance_val')
    distance_unit = params.get('distance_unit', 'Mpc')
    norm_global = bool(params.get('norm_global', False))
    user_vmin_raw = params.get('user_vmin')
    user_vmax_raw = params.get('user_vmax')
    cbar_unit = params.get('cbar_unit', 'None')
    invert_mask = bool(params.get('invert_mask', False))

    # Format values as Python literals
    center_x_lit = repr(float(center_x_raw)) if center_x_raw is not None else 'None'
    center_y_lit = repr(float(center_y_raw)) if center_y_raw is not None else 'None'
    distance_val_lit = repr(float(distance_val_raw)) if distance_val_raw else 'None'
    user_vmin_lit = repr(float(user_vmin_raw)) if user_vmin_raw and str(user_vmin_raw).strip() else 'None'
    user_vmax_lit = repr(float(user_vmax_raw)) if user_vmax_raw and str(user_vmax_raw).strip() else 'None'
    mask_path_lit = repr(mask_path) if mask_path else 'None'

    view_desc = f"channel {channel}" if view_type == 'cube' else f"moment {moment_type}"

    config_section = f'''#!/usr/bin/env python3
"""
Generated by CubeFig
View: {view_type.capitalize()} {view_desc}
File: {file_path}
"""

# ============================================================
# CONFIGURATION - modify these to adjust the output
# ============================================================
FILE_PATH = {repr(file_path)}
MASK_PATH = {mask_path_lit}

VIEW_TYPE = {repr(view_type)}    # "cube" or "moment"
CHANNEL = {channel}              # Channel index (used when VIEW_TYPE = "cube")
MOMENT_TYPE = {repr(moment_type)}  # "0", "1", or "2" (used when VIEW_TYPE = "moment")
START_CHAN = {start_chan}         # Channel range start for moment computation
END_CHAN = {end_chan}             # Channel range end for moment computation

TITLE = {repr(title)}
FIG_WIDTH = {fig_width}
FIG_HEIGHT = {fig_height}
GRID = {grid}
SHOW_BEAM = {show_beam}
SHOW_CENTER = {show_center}
CENTER_X = {center_x_lit}        # Pixel coordinate
CENTER_Y = {center_y_lit}        # Pixel coordinate
SHOW_OFFSET = {show_offset}
OFFSET_ANGLE_UNIT = {repr(offset_angle_unit)}
SHOW_PHYSICAL = {show_physical}
DISTANCE_VAL = {distance_val_lit}  # Distance in parsecs
DISTANCE_UNIT = {repr(distance_unit)}
NORM_GLOBAL = {norm_global}
USER_VMIN = {user_vmin_lit}
USER_VMAX = {user_vmax_lit}
CBAR_UNIT = {repr(cbar_unit)}
INVERT_MASK = {invert_mask}

OUTPUT_FILE = "cubefig_plot.pdf"  # Change to .png or .svg as needed

'''

    static_section = r'''# ============================================================
# IMPORTS
# ============================================================
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from astropy.io import fits
from astropy.wcs import WCS
from astropy.visualization import ZScaleInterval
from astropy import units as u
from astropy.wcs.utils import proj_plane_pixel_scales
from mpl_toolkits.axes_grid1 import make_axes_locatable
from matplotlib.patches import Ellipse
from matplotlib.colors import to_rgba

# ============================================================
# MATPLOTLIB SETTINGS
# ============================================================
plt.rcParams.update({
    "text.usetex": True,
    "font.family": "serif",
    "font.serif": ["Computer Modern Roman"],
    "font.size": 12,
    "axes.labelsize": 12,
    "legend.fontsize": 10,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10,
})

# ============================================================
# HELPER FUNCTIONS
# ============================================================
def draw_beam(ax, wcs_2d, beam, image_shape):
    if not beam or not beam.get('bmaj'):
        return
    try:
        scales = proj_plane_pixel_scales(wcs_2d)
        bmaj_pix = beam['bmaj'] / scales[1]
        bmin_pix = beam['bmin'] / scales[0]
        bpa = beam['bpa']
        h, w = image_shape
        offset = 0.05 * min(h, w)
        bx = offset + bmaj_pix / 2
        by = offset + bmaj_pix / 2
        edge_rgba = to_rgba('black', 1.0)
        face_rgba = to_rgba('gray', 0.5)
        beam_ell = Ellipse((bx, by), bmin_pix, bmaj_pix, angle=bpa,
                           edgecolor=edge_rgba, facecolor=face_rgba, linewidth=1)
        ax.add_patch(beam_ell)
        rad_pa = np.radians(bpa)
        dx_maj = -(bmaj_pix / 2) * np.sin(rad_pa)
        dy_maj = (bmaj_pix / 2) * np.cos(rad_pa)
        axis_rgba = to_rgba('black', 1.0)
        ax.plot([bx - dx_maj, bx + dx_maj], [by - dy_maj, by + dy_maj],
                color=axis_rgba, linewidth=1)
        dx_min = (bmin_pix / 2) * np.cos(rad_pa)
        dy_min = (bmin_pix / 2) * np.sin(rad_pa)
        ax.plot([bx - dx_min, bx + dx_min], [by - dy_min, by + dy_min],
                color=axis_rgba, linewidth=1)
    except Exception as e:
        print(f"Warning: Could not draw beam: {e}")


def draw_physical_axes(ax, wcs_2d, show_physical, show_center,
                       center_x, center_y, distance_val, distance_unit):
    if not (show_physical and show_center
            and center_x is not None and center_y is not None and distance_val):
        return
    try:
        cx_pix, cy_pix = float(center_x), float(center_y)
        d_pc = float(distance_val) * u.pc
        pixscale_deg = proj_plane_pixel_scales(wcs_2d)
        target_unit = u.Unit(distance_unit)
        upp_x = ((pixscale_deg[0] * u.deg).to(u.rad).value * d_pc).to(target_unit).value
        upp_y = ((pixscale_deg[1] * u.deg).to(u.rad).value * d_pc).to(target_unit).value

        def pix2phys_x(pix):
            return (np.asarray(pix, dtype=float) - cx_pix) * upp_x

        def phys2pix_x(phys):
            return cx_pix + np.asarray(phys, dtype=float) / upp_x

        def pix2phys_y(pix):
            return (np.asarray(pix, dtype=float) - cy_pix) * upp_y

        def phys2pix_y(phys):
            return cy_pix + np.asarray(phys, dtype=float) / upp_y

        ax_top = ax.secondary_xaxis("top", functions=(pix2phys_x, phys2pix_x))
        ax_top.set_xlabel(rf"$\Delta x$ [{distance_unit}]", labelpad=15)
        ax_right = ax.secondary_yaxis("right", functions=(pix2phys_y, phys2pix_y))
        ax_right.set_ylabel(rf"$\Delta y$ [{distance_unit}]", rotation=270, labelpad=15)
        if hasattr(ax, "coords"):
            ax.coords[0].set_ticks_position("b")
            ax.coords[0].set_axislabel_position("b")
            ax.coords[1].set_ticks_position("l")
            ax.coords[1].set_axislabel_position("l")
    except Exception as e:
        print(f"Error adding physical axes: {e}")


def compute_moment(data, wcs, bunit, start_chan, end_chan, moment_type,
                   mask=None, invert_mask=False):
    start = max(0, int(start_chan))
    end = min(data.shape[0], int(end_chan) + 1)
    subset = data[start:end, :, :].copy().astype(float)
    if mask is not None:
        mask_subset = mask[start:end, :, :]
        if invert_mask:
            keep = np.logical_or(mask_subset <= 0, np.isnan(mask_subset))
        else:
            keep = mask_subset > 0
        subset = np.where(keep, subset, np.nan)
    try:
        spec_wcs = wcs.spectral
        pixel_coords = np.arange(start, end)
        world_coords = spec_wcs.pixel_to_world(pixel_coords)
        try:
            v = world_coords.to('km/s').value
            v_unit = 'km/s'
        except Exception:
            v = world_coords.value
            v_unit = str(world_coords.unit)
    except Exception:
        v = np.arange(start, end, dtype=float)
        v_unit = 'pixels'
    v = v.astype(float)
    dv = abs(v[1] - v[0]) if len(v) > 1 else 1.0
    sum_i = np.nansum(subset, axis=0)
    if moment_type == '0':
        return sum_i * dv, f"{bunit} {v_unit}"
    sum_i_safe = np.where(sum_i == 0, np.nan, sum_i)
    mom1 = np.nansum(subset * v[:, None, None], axis=0) / sum_i_safe
    if moment_type == '1':
        return mom1, v_unit
    res_sq = (v[:, None, None] - mom1[None, :, :]) ** 2
    mom2 = np.sqrt(np.nansum(subset * res_sq, axis=0) / sum_i_safe)
    return mom2, v_unit


def create_plot(image_data, wcs, unit_label, title, grid, beam, show_beam,
                show_center, center_x, center_y, show_physical, distance_val,
                distance_unit, norm_global, global_min, global_max,
                user_vmin, user_vmax, cbar_unit, show_offset, offset_angle_unit,
                fig_width, fig_height, cbar_label, output_file):

    wcs_2d = wcs.celestial
    fig = plt.figure(figsize=(fig_width, fig_height))

    if show_offset and center_x is not None and center_y is not None:
        wcs_axes = wcs_2d.deepcopy()
        try:
            wcs_axes.wcs.crpix = [float(center_x) + 1, float(center_y) + 1]
            wcs_axes.wcs.crval = [0, 0]
            wcs_axes.wcs.ctype = ["LINEAR", "LINEAR"]
            if offset_angle_unit == 'milliarcsec':
                angle_multiplier = 3600.0 * 1000.0
                unit_str = 'mas'
            else:
                angle_multiplier = 3600.0
                unit_str = 'arcsec'
            if hasattr(wcs_axes.wcs, 'cdelt'):
                wcs_axes.wcs.cdelt = [d * angle_multiplier for d in wcs_axes.wcs.cdelt]
            if hasattr(wcs_axes.wcs, 'cd'):
                wcs_axes.wcs.cd = wcs_axes.wcs.cd * angle_multiplier
            ax = plt.subplot(projection=wcs_axes)
            ax.set_xlabel(rf'$\Delta$ RA [{unit_str}]')
            ax.set_ylabel(rf'$\Delta$ Dec [{unit_str}]')
        except Exception as e:
            print(f"Error creating offset WCS: {e}")
            ax = plt.subplot(projection=wcs_2d)
            ax.set_xlabel('Right Ascension [J2000]')
            ax.set_ylabel('Declination [J2000]')
    else:
        ax = plt.subplot(projection=wcs_2d)
        ax.set_xlabel('Right Ascension [J2000]')
        ax.set_ylabel('Declination [J2000]')

    scale_factor = 1.0
    unit_prefix = ""
    if cbar_unit == 'milli':
        scale_factor = 1e3
        unit_prefix = "m"
    elif cbar_unit == 'micro':
        scale_factor = 1e6
        unit_prefix = r"$\mu$"
    elif cbar_unit == 'nano':
        scale_factor = 1e9
        unit_prefix = "n"
    plot_data = image_data * scale_factor
    scaled_min = (global_min * scale_factor) if global_min is not None else None
    scaled_max = (global_max * scale_factor) if global_max is not None else None
    final_unit_label = f"{unit_prefix}{unit_label}"

    if norm_global and scaled_min is not None and scaled_max is not None:
        vmin, vmax = scaled_min, scaled_max
    else:
        if np.any(np.isfinite(plot_data)):
            interval = ZScaleInterval()
            vmin, vmax = interval.get_limits(plot_data)
        else:
            vmin, vmax = 0, 1

    if user_vmin is not None:
        try:
            vmin = float(user_vmin)
        except (ValueError, TypeError):
            pass
    if user_vmax is not None:
        try:
            vmax = float(user_vmax)
        except (ValueError, TypeError):
            pass

    im = ax.imshow(plot_data, origin='lower', cmap='viridis', vmin=vmin, vmax=vmax)

    if grid:
        ax.coords.grid(True, ls='dotted')

    if show_beam:
        draw_beam(ax, wcs_2d, beam, image_data.shape)

    if show_center and center_x is not None and center_y is not None:
        try:
            ax.plot(float(center_x), float(center_y), marker='*', color='red',
                    markersize=12, markeredgecolor='black', markeredgewidth=1)
        except Exception as e:
            print(f"Error drawing center marker: {e}")

    draw_physical_axes(ax, wcs_2d, show_physical, show_center,
                       center_x, center_y, distance_val, distance_unit)

    if title:
        ax.set_title(title, pad=15, fontsize=14)

    ax.tick_params(direction='out', color='black')

    divider = make_axes_locatable(ax)
    cbar_pad = 0.85 if (show_physical and show_center and center_x is not None) else 0.25
    cax = divider.append_axes("right", size="5%", pad=cbar_pad, axes_class=plt.Axes)
    cbar = plt.colorbar(im, cax=cax)
    cax.tick_params(axis='x', which='both', bottom=False, top=False)
    cax.tick_params(axis='y', which='both', left=False, right=True)
    if not (final_unit_label.startswith('[') and final_unit_label.endswith(']')):
        final_unit_label = f"[{final_unit_label}]"
    cbar.set_label(f'{cbar_label} {final_unit_label}', rotation=270, labelpad=20)

    fmt = output_file.rsplit('.', 1)[-1] if '.' in output_file else 'pdf'
    plt.savefig(output_file, format=fmt, dpi=150, bbox_inches='tight', pad_inches=0.05)
    plt.close(fig)
    print(f"Saved: {output_file}")


# ============================================================
# LOAD DATA
# ============================================================
with fits.open(FILE_PATH) as hdul:
    raw_data = hdul[0].data
    hdr = hdul[0].header
    if raw_data is None and len(hdul) > 1:
        raw_data = hdul[1].data
        hdr = hdul[1].header
    data = np.squeeze(raw_data).astype(float)
    wcs = WCS(hdr)
    unit = hdr.get('BUNIT', 'Arbitrary Units').strip()
    beam = {
        'bmaj': hdr.get('BMAJ'),
        'bmin': hdr.get('BMIN'),
        'bpa':  hdr.get('BPA', 0),
    }
    global_min = float(np.nanmin(data))
    global_max = float(np.nanmax(data))

mask = None
if MASK_PATH is not None:
    with fits.open(MASK_PATH) as mhdul:
        mask_raw = mhdul[0].data
        if mask_raw is None and len(mhdul) > 1:
            mask_raw = mhdul[1].data
        mask_data = np.squeeze(mask_raw)
        if mask_data.ndim == 2:
            mask = np.repeat(mask_data[np.newaxis, :, :], data.shape[0], axis=0)
        else:
            mask = mask_data.astype(float)

# ============================================================
# PREPARE VIEW DATA
# ============================================================
if VIEW_TYPE == "cube":
    image_data = data[CHANNEL, :, :].copy()
    if mask is not None:
        mask_slice = mask[CHANNEL, :, :]
        if INVERT_MASK:
            keep = np.logical_or(mask_slice <= 0, np.isnan(mask_slice))
        else:
            keep = mask_slice > 0
        image_data = np.where(keep, image_data, np.nan)
    cbar_label = "Specific Intensity"
    final_title = TITLE
else:
    image_data, unit = compute_moment(
        data, wcs, unit, START_CHAN, END_CHAN, MOMENT_TYPE,
        mask=mask, invert_mask=INVERT_MASK
    )
    cbar_labels = {"0": "Intensity", "1": "Velocity Field", "2": "Velocity Dispersion"}
    cbar_label = cbar_labels.get(MOMENT_TYPE, "Intensity")
    final_title = f"{TITLE}\nMoment {MOMENT_TYPE}" if TITLE else f"Moment {MOMENT_TYPE}"

# ============================================================
# CREATE PLOT
# ============================================================
create_plot(
    image_data, wcs, unit,
    title=final_title,
    grid=GRID,
    beam=beam,
    show_beam=SHOW_BEAM,
    show_center=SHOW_CENTER,
    center_x=CENTER_X,
    center_y=CENTER_Y,
    show_physical=SHOW_PHYSICAL,
    distance_val=DISTANCE_VAL,
    distance_unit=DISTANCE_UNIT,
    norm_global=NORM_GLOBAL,
    global_min=global_min,
    global_max=global_max,
    user_vmin=USER_VMIN,
    user_vmax=USER_VMAX,
    cbar_unit=CBAR_UNIT,
    show_offset=SHOW_OFFSET,
    offset_angle_unit=OFFSET_ANGLE_UNIT,
    fig_width=FIG_WIDTH,
    fig_height=FIG_HEIGHT,
    cbar_label=cbar_label,
    output_file=OUTPUT_FILE,
)
'''

    return config_section + static_section
